services:
  - type: web
    name: smile-financial-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
